#!/bin/bash

# Check if the bucket name argument is provided
if [ -z "$1" ]; then
  echo "Usage: $0 <bucket-name>"
  exit 1
fi
if [ -z "$2" ]; then
  echo "Usage: $0 <key-name>"
  exit 1
fi
BUCKET_NAME=$1
KEY=$2

echo "Deleting object: $KEY"

aws s3api delete-object \
  --bucket "$BUCKET_NAME" \
  --key "$KEY"